### ISSUE TITLE
openvhook compatibility

### ISSUE THREAD

**Issue by BenjaminGTACoder** [E66666666/GTAVMenuExample#2]
Hello ikt, it is me again haha :)

I cannot find a way to make images draw with openvhook, I do not suppose you would be able to work on image rendering in openvhook?

I understand if not, it is a great task.
Thank you for your mods.

**Comment by ikt32** [comment]
My fork of OpenVHook doesn't have any texture implementation. [This](https://github.com/ivanmeler/OpenVHook/tree/master/OpenVHook) fork should be more up-to-date. That said, that one also doesn't have image drawing support yet, and I wouldn't know how to. MAFINS (Menyoo author) probably has it figured out, so try getting him to contribute to ivanmeler's OpenVHook fork :P

Since this issue isn't related to the menu itself, issue closed.
